default: &default
  adapter: mysql2
  encoding: unicode

production:
  <<: *default
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
